#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorXmlDemo
{
    using System;
    
    #line 3 "..\..\Template.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Template.cshtml"
    using RazorXmlDemo;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Template : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 6 "..\..\Template.cshtml"

public IEnumerable<XmlModel> Model { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");


WriteLiteral("\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<People>\r\n");


            
            #line 11 "..\..\Template.cshtml"
     foreach (var m in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <Person>\r\n            <FirstName>");


            
            #line 14 "..\..\Template.cshtml"
                  Write(m.FirstName);

            
            #line default
            #line hidden
WriteLiteral("</FirstName>\r\n            <LastName>");


            
            #line 15 "..\..\Template.cshtml"
                 Write(m.LastName);

            
            #line default
            #line hidden
WriteLiteral("</LastName>\r\n        </Person>\r\n");


            
            #line 17 "..\..\Template.cshtml"
    }    

            
            #line default
            #line hidden
WriteLiteral("</People>\r\n");


        }
    }
}
#pragma warning restore 1591
